# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  WORK_NAME: proposal
  TARGET_FILE: "research\ proposal.pdf"

tasks:
  default:
    desc: Build the Research Proposal
    cmds:
      - typst compile "{{.WORK_NAME}}.typ" "{{.TARGET_FILE}}"
    silent: true
