# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  WORK_NAME: thesis
  TARGET_FILE: "thesis.pdf"

tasks:
  default:
    desc: Build the thesis
    cmds:
      - typst compile "{{.WORK_NAME}}.typ" "{{.TARGET_FILE}}"
    silent: true
